# To build, run the following command from the top level project directory:
#
# docker build -f src/main/docker/Dockerfile .

ARG BUILD_ENV=container

FROM registry.access.redhat.com/ubi9/openjdk-21:latest as build-container
USER 0
WORKDIR /application
COPY src src
COPY pom.xml .
RUN mvn package && \
    java -Djarmode=layertools -jar target/*.jar extract && \
    # CRYOSTAT
    cp target/dependency/cryostat-agent-shaded.jar /application/dependencies/

FROM quay.io/hummingbird/openjdk:21-runtime as build-local
USER 0
WORKDIR /application
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract && chown -R 1001:0 /application && \
    chmod -R g=u /application

FROM build-${BUILD_ENV} as intermediate

FROM quay.io/hummingbird/openjdk:21-runtime
USER 1001
WORKDIR /application
COPY --from=intermediate \
     /application/dependencies/ \
     /application/spring-boot-loader/ \
     /application/snapshot-dependencies/ \
     /application/application/ \
     ./

CMD ["java", "-javaagent:cryostat-agent-shaded.jar", "org.springframework.boot.loader.launch.JarLauncher"]
# CMD ["java", "-Dcom.sun.management.jmxremote.port=9091", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", "org.springframework.boot.loader.launch.JarLauncher"]
