kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: java-sample
  labels:
    app: java-sample
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: {{ .Values.buildConfig.to.image }}
    pushSecret:
      name: {{ .Values.buildConfig.to.pushSecret }}
    imageLabels:
    - name: app
      value: java-sample
    - name: maintainer
      value: tbox
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.buildConfig.from.image }}
      pullSecret:
        name: {{ .Values.buildConfig.from.pullSecret }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jboss-openshift/openshift-quickstarts'
    contextDir: undertow-servlet
  runPolicy: Serial
