name: nodejs-ex

on:
  push:
    branches:
      - actions

env:
  IMAGE_NAME: nodejs-ex
  TAGS: latest

jobs:
  s2i-build:
    name: Build and deploy nodejs-ex
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to Red Hat Registry using Docker
      uses: docker/login-action@v1
      with:
        registry: registry.redhat.io
        username: '11009103|trevorbot'
        password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}

    # - name: Log in to Red Hat Registry
    #   uses: redhat-actions/podman-login@v1
    #   with:
    #     username: '11009103|trevorbot'
    #     password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
    #     registry: registry.redhat.io
 
    # Setup S2i and Build container image
    - name: Setup and Build
      id: build_image
      uses: redhat-actions/s2i-build@v2
      with:
        path_context: './examples/nodejs/app'
        builder_image: 'registry.redhat.io/rhel8/nodejs-14:latest'
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAGS }}

    # Push Image to Quay registry
    - name: Push To Quay Action
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: quay.io/trevorbox
        username: "trevorbox+deployer"
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
