name: nodejs-ex-buildah

on:
  push:
    branches:
      - actions

env:
  IMAGE_NAME: nodejs-ex-minimal
  TAGS: latest
  REGISTRY: quay.io/trevorbox
  QUAY_IO_USERNAME: ${{ secrets.QUAY_IO_USERNAME }}
  QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
  REGISTRY_REDHAT_IO_USERNAME: ${{ secrets.REGISTRY_REDHAT_IO_USERNAME }}
  REGISTRY_REDHAT_IO_PASSWORD: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}

jobs:
  buildah-build:
    name: Build and deploy nodejs-ex-minimal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Red Hat Registry using Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ env.REGISTRY_REDHAT_IO_USERNAME }}
          password: ${{ env.REGISTRY_REDHAT_IO_PASSWORD }}
          logout: false
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          content: './examples/nodejs/app'
          dockerfiles: |
            ./examples/nodejs/app/Dockerfile
      # Push Image to Quay registry
      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.QUAY_IO_USERNAME }}
          password: ${{ env.QUAY_IO_PASSWORD }}
